robosuite/wrappers/ik_wrapper.py
- Fixed a small issue with the IKWrapper for resetting the controller between episode resets.
=> fix reset issue for ik_wrapper

docs/creating_environment.md
=> minor_env_doc_issue

robosuite/controllers/baxter_ik_controller.py, robosuite/controllers/sawyer_ik_controller.py, robosuite/wrappers/ik_wrapper.py
- added `action_repeat` parameter to `IKWrapper` to allow for end effector control to happen at a different rate than the low-level joint control
=> adding support for different IK control freq from low level freq

robosuite/scripts/collect_human_demonstrations.py, robosuite/wrappers/ik_wrapper.py
- some small fixes to fix deterministic action replay from collected demonstrations
=> fixing action replay from demos

robosuite/environments/panda.py, robosuite/environments/sawyer.py
image_width = image_width, not image_height
=> fix bug for non-square images

robosuite/environments/panda_lift.py, robosuite/environments/panda_stack.py, robosuite/environments/sawyer_lift.py, robosuite/environments/sawyer_stack.py, robosuite/models/tasks/placement_sampler.py
- Fixing a bug where cube for lift task is always initialized with constant rotation.
=> Fix lift initialization

robosuite/environments/panda.py, robosuite/environments/sawyer.py, robosuite/environments/sawyer_lift.py, robosuite/environments/sawyer_nut_assembly.py, robosuite/models/tasks/__init__.py, robosuite/models/tasks/placement_sampler.py, robosuite/scripts/tune_camera.py, robosuite/utils/mjcf_utils.py
- functionality for reproducible evaluations on a grid of initializations for both Lift and Nut Assembly
=> vices grid eval

robosuite/scripts/tune_camera.py
- Wrote a script to easily tune cameras by using the keyboard in an interactive viewer session.
=> adding script to tune camera

robosuite/controllers/arm_controller.py, robosuite/utils/transform_utils.py
- option for rotation action space to be axis-angle
- changed rotation error computation to use axis-angle
- support for force perturbations in both axis-angle and euler representation
- TODO (danfei): should we get rid of Euler action space and default to axis-angle?
=> adding axis angle computations to vices

robosuite/controllers/base_controller.py
- The current indexing of the mass matrix is wrong. This should fix it.
=> Fixing OSC mass matrix indexing

robosuite/wrappers/data_collection_wrapper.py
Adding logic to handle the following error ``` KeyError: 'gripper_actuation  ``` while collecting demonstration data using panda.
=> Fix to solve error in gather_demonstrations_as_hdf5 (panda)

MANIFEST.in, setup.py
=> Fix robosuite v1.0 packaging issue with controllers

robosuite/controllers/osc.py
Fix osc controller, as per #139
=> Fix Absolute OSC Control

robosuite/controllers/osc.py, robosuite/utils/control_utils.py
- Replace some inverses with pseudoinverses to address #136
=> Update opspace inverses to be pseudoinverses

robosuite/models/objects/objects.py
Fix issue xml object naming bug (#149)
=> fix xml object naming bug

robosuite/robots/bimanual.py
=> fix bimanual obs construction (#152)

robosuite/environments/robot_env.py
=> Fix a bug of returning same image for different camera views in obs

README.md
One-line change of version number on README.md
=> update version number to v1.2

docs/references.md
Please let me know if I missed any. These papers are pulled from Google Scholar based on the citations.
=> Update robosuite reference list

docs/conf.py, docs/installation.md, docs/overview.md, requirements.txt, setup.py
Make the dependencies between `requirements.txt` and `setup.py` consistent, and add compiling instructions for macOS platforms
=> update installation dependencies and instructions

robosuite/models/assets/bullet_data/baxter_description/urdf/baxter_arm.urdf, robosuite/models/assets/bullet_data/sawyer_description/urdf/sawyer_arm.urdf
=> Update lower case file names in URDF files

docs/references.md
Additional references to robosuite via surreal
=> Additional surreal citations

robosuite/__init__.py, setup.py
Due to texture changes from Abhishek's PR
=> Update version number to v1.3.1

robosuite/renderers/igibson/igibson_utils.py, robosuite/renderers/igibson/parser.py
- Fix geom type detection and scale for sphere type objects in iGibson parser
=> Fix sphere geoms with iGibson rendering

robosuite/environments/manipulation/single_arm_env.py, robosuite/environments/manipulation/two_arm_env.py
Fixes "No Site Named..." error from call to eef_xmat in single_arm_env and two_arm_env (#321)
=> Fix No Site Error

.pre-commit-config.yaml, robosuite/renderers/igibson/igibson_renderer.py, robosuite/renderers/igibson/igibson_utils.py, robosuite/renderers/igibson/parser.py, robosuite/scripts/collect_human_demonstrations.py, robosuite/wrappers/data_collection_wrapper.py
Modify DataCollectionWrapper and collect_human_demonstrations script to save only successful demonstrations to dataset, and disregard any unsuccessful demonstrations.
=> Modify DataCollectionWrapper and collect_human_demonstrations script to save only successful demonstrations

robosuite/renderers/nvisii/nvisii_utils.py, robosuite/renderers/nvisii/parser.py
Fixes the same issue with getting geom types as #307 for the NVISII renderer.
=> Fix sphere geoms with NVISII renderer

robosuite/robots/bimanual.py, robosuite/robots/single_arm.py
Contributions:
- -Reset gripper current_action at robot reset calls (see issue #386 )
=> Resolve #386: Reset current_action of grippers at robot reset (SingleArm and Bimanual)

docs/installation.md
add a note in installation docs page recommending advanced users to install from source.
=> note about installing from source

requirements-extra.txt, robosuite/demos/demo_gym_functionality.py, robosuite/wrappers/gym_wrapper.py
for reference: https://gymnasium.farama.org/content/migration-guide/
=> ports gym wrapper to gymnasium

robosuite/environments/base.py
See issue here: https://github.com/ARISE-Initiative/robosuite/issues/388
credits to @tadashiK for bringing up the issue
=> hard resets: setup observables correctly when there's a viewer

robosuite/environments/manipulation/pick_place.py, robosuite/models/assets/base.xml, robosuite/models/objects/generated_objects.py, robosuite/models/objects/objects.py, robosuite/models/objects/primitive/ball.py, robosuite/models/objects/primitive/box.py, robosuite/models/objects/primitive/capsule.py, robosuite/models/objects/primitive/cylinder.py, robosuite/wrappers/wrapper.py
- fix bug in wrapper
- edit compiler options to enable autolimits (see [this link](https://mujoco.readthedocs.io/en/stable/XMLreference.html#compiler-autolimits) - the default value will change to true in a future MuJoCo release anyways)
- API functionality for composite body
=> some minor changes

docs/installation.md
Adding common issues and solutions found when installing Robosuite in a Windows environment.
=> Updating Docs with Windows Installation Steps

README.md
See changes in text. Pending latest gallery of robots image.
=> Update Readme for v1.5.0

robosuite/demos/demo_video_recording.py
Print video save path in demo vid recording
```python robosuite/demos/demo_video_recording.py```
=> Print video save path in demo vid recording

.github/workflows/update-docs.yaml
Creates a workflow to automatically update the docs when new commits are made to master.
=> Adding doc update workflow

.github/workflows/update-docs.yaml, docs/modules/renderers.md
Fixes the issue of automatically generating a .nojekyll file. Adds a new commit in gh-pages called "Remove .nojekyll file" when a .jekyll file is automatically created.
=> Documention CI Update .nojekyll fix

docs/modules/controllers.rst, docs/tutorials/add_environment.md
=> Fix doc links

.github/workflows/update-docs.yaml, docs/conf.py
Fix device doc compilation issue.
=> Fix-device-docs-I

docs/demos.md
=> small update to demos page

.github/workflows/run-tests.yaml, .github/workflows/update-pypi.yaml
Adds a github workflow for PyPI.
=> Adding pypi workflow

docs/changelog.md
Update v1.5.1 changelog for v1.5.1 release
=> Update v1.5.1 changelog

robosuite/models/assets/robots/sawyer/robot.xml
Add shell inertia to small meshes in Sawyer robot.
=> Adding shell inertia for meshes in Sawyer

robosuite/robots/robot.py
=> [add] add sensors

requirements-extra.txt, setup.py
Fixes #744 
pin mink version and remove it from requirements-extra since its in setup.py
=> Pin mink version
