docs/demonstrations.md
robosuite/scripts/collect_human_demonstrations.py
robosuite/scripts/playback_demonstrations_from_hdf5.py
robosuite/wrappers/data_collection_wrapper.py

- Added functionality for deterministic open loop playback of actions from demonstrations. Note that this only applies to new demonstrations that are collected with these changes (old demonstrations will not playback correctly).
- Fixed a bug where we were possible dropping a few intermediate (s, a) pairs during data collection.

action playback

---

robosuite/environments/baxter.py
robosuite/environments/baxter_lift.py
robosuite/environments/baxter_peg_in_hole.py
robosuite/environments/sawyer.py
robosuite/environments/sawyer_nut_assembly.py
robosuite/environments/sawyer_pick_place.py

- There can be subtle bugs with modifying certain observation keys in-place if copies are not returned. Fixing some of those issues by ensuring copies are returned for those keys.

copy observations before returning them

---

robosuite/environments/baxter.py
robosuite/environments/sawyer.py

This fixes an issue in reset function.
In the original code, `self._ref_joint_gripper_right_actuator_indexes` and `self._ref_joint_gripper_left_actuator_indexes` contain indexes of the left wrist.
`self._ref_gripper_right_joint_pos_indexes` and `self._ref_gripper_left_joint_pos_indexes` should be used instead of them.

fix reset issue for sawyer and baxter with grippers

---

robosuite/environments/base.py
robosuite/environments/manipulation/door.py
robosuite/environments/manipulation/lift.py
robosuite/environments/manipulation/manipulation_env.py
robosuite/environments/manipulation/nut_assembly.py
robosuite/environments/manipulation/pick_place.py
robosuite/environments/manipulation/stack.py
robosuite/environments/manipulation/two_arm_handover.py
robosuite/environments/manipulation/two_arm_lift.py
robosuite/environments/manipulation/two_arm_peg_in_hole.py
robosuite/environments/manipulation/wipe.py
robosuite/environments/robot_env.py

- All environments now have an argument called `render_gpu_device_id` allowing for selection of GPU device to use for offscreen rendering. This is important for multi-GPU machines.

Adding option to select GPU device for offscreen renderer

---

robosuite/scripts/tune_camera.py
robosuite/utils/mjcf_utils.py

Resolve #154, now `tune_camera.py` script can handle both inputted camera tags or simply camera names (will initialize cameras to their default sim location), and can also tune nested cameras as well that don't exist at the top worldbody level.

Fix tune camera

---

robosuite/scripts/collect_human_demonstrations.py
robosuite/scripts/playback_demonstrations_from_hdf5.py
robosuite/wrappers/data_collection_wrapper.py
robosuite/wrappers/demo_sampler_wrapper.py

- fix some errors that we had in our scripts and data collection from the v1.0 refactor to enable deterministic action playback
- address #173 and #162

repair deterministic playback

---

robosuite/models/assets/robots/jaco/robot.xml
robosuite/models/assets/robots/kinova3/robot.xml
robosuite/models/assets/robots/ur5e/robot.xml
tests/test_robots/test_all_robots.py

- Fixed  `contact_geoms` for `Kinova3`, `Jaco` and `UR5e` robot. It is now possible to use these robots with the `Wipe` environment.
- Created a simple test for checking the `contact_geoms`.

Fix contact geoms bug

---

robosuite/controllers/controller_factory.py
robosuite/controllers/interpolators/linear_interpolator.py
robosuite/controllers/joint_pos.py
robosuite/controllers/joint_tor.py
robosuite/controllers/joint_vel.py

- Fixed a bug where the interpolator `dim` is changed, but not the dimension of `goal` state and `start` state. 
- Corrected the call of the `get_interpolated_goal()` method for joint controllers.

Fix interpolator dim bug

---

robosuite/utils/input_utils.py

Add OSC_POSITION option in spacemouse input_utils

---

robosuite/controllers/osc.py

The current default value of [set_ori](https://github.com/ARISE-Initiative/robosuite/blob/2a34f81983877852009b64ec3a7eae7efcffe001/robosuite/controllers/osc.py#L237) has -1 determinant which happens to be an improper rotation.
I noticed that the default eef orientation is pointing in positive z axis. If we need the eef to point down, we should
1. First rotate 180 degrees about the x axis (multiply by Rx(180).
2. Then rotate 90 degrees about the z axis (multiply by Rz(90).
Applying these two transformations to an identity matrix results in the new rotation matrix values included in this PR. 
I've verified the behaviour of the new default orientation on all single armed robot types.
Please find the images attached showing the above transformations.
Fixes #230.

Fixed default control for orientation in OSC

---

robosuite/models/assets/robots/jaco/robot.xml

Remove collisions between Jaco base and 1st joint collision geoms to prevent 1st joint from being stuck

Fix Jaco Collision Geoms

---

docs/quickstart.md

1. `gripper.hide_visualization()` is deprecated.
2. `get_collision` is deprecated and should be replaced by `get_obj`.
3. there's already a free joint that is enabled by default. Adding an
extra one lead to error when `model = world.get_model(mode="mujoco_py")`

Fix quickstart documentation.

---

robosuite/controllers/config/joint_velocity.json
robosuite/controllers/joint_vel.py

Fixes #201. Removes the joint velocity observation clipping during the controller computation causing inaccurate results, and increases the default kp gain value for faster convergence.

Fix Joint Velocity Bug

---

docs/installation.md
requirements.txt
setup.py

Updates dependencies for compatibility with new free version of Mujoco. more info: https://github.com/openai/mujoco-py/pull/640. Resolves #262

replaced mujoco-py with free-mujoco-py version 2.1.0 from DM

---

docs/demos.md
requirements-extra.txt
robosuite/controllers/ik.py

The SVL PyBullet version is needed for the iGibson renderer. I also verified that it is compatible with the IK controller. I thus proposed to update our pybullet dependency to this version.

Switch to use SVL PyBullet release version

---

robosuite/models/assets/robots/panda/robot.xml
setup.py

A quick fix on the basic requirement and missing link 7 collision mesh.

Update basic requirement in setup and missing link 7 collision mesh panda

---

robosuite/models/assets/bullet_data/panda_description/urdf/panda_arm.xacro
robosuite/models/assets/bullet_data/panda_description/urdf/panda_arm_hand.urdf

Hi, 
This pr fixes a bug in 'panda_arm.xacro' and 'panda_arm_hand.urdf' where the xyz value for the 'panda_joint1' joint is wrong. Specifically, the value `<origin rpy="0 0 0" xyz="0 -0.1 0"/>` needs to change to `<origin rpy="0 0 0" xyz="0 0 0.333"/>`. The `0 0 0.333` value is used here as well: https://github.com/ros-planning/moveit_resources/blob/master/panda_description/urdf/panda_arm.xacro#L38
Currently:
With fix:
I brought this up previously here: https://github.com/ARISE-Initiative/robosuite/issues/371
Thanks! Let me know if you all need any other info, this is my first pr to this repo so i'm not sure what's expected.

bug fix - panda_arm_hand.urdf, panda_arm.xacro have the wrong origin for 'panda_joint1'

---

robosuite/__init__.py
robosuite/macros.py
robosuite/utils/log_utils.py

* set unique logging file name: `/tmp/robosuite_{time}_{pid}.log`
* set file logging to `None` by default in `macros.py` (I figured this isn't a critical feature right now)

logging fixes

---

robosuite/__init__.py
robosuite/devices/keyboard.py
robosuite/devices/spacemouse.py
robosuite/macros.py

* try to import `macros_private.py` inside `macros.py`
* change the default spacemouse product id from `50735` to `50734`
* remove `ESC` option in `keyboard.py` and `spacemouse.py` -- we never have supported this
* fix bug in `spacemouse.py` when referencing spacemouse product id (use the value specified to constructor rather than the macro value)

fix macro issues from issue #385

---

robosuite/models/arenas/multi_table_arena.py

- import `Iterable` from the correct module in `robosuite/models/arenas/multi_table_arena.py`
- resolve #355

fix Iterable import for python 3.10 in multi_table_arena

---

robosuite/utils/placement_samplers.py

Corrected an outdated docstring for _sample_quat() method of UniformRandomSampler. Resolves #413

Minor internal documentation fix

---

robosuite/models/assets/robots/kinova3/robot.xml

In the [robot.xml](https://github.com/otokatli/robosuite/blob/master/robosuite/models/assets/robots/kinova3/robot.xml) file for Kinova Gen3 robot, there is a minor mistake about the link length of the last link for the robot.
In body `right_hand` the length is defined as 0.65. However, if you check the [Kinova Gen3 manual](https://www.kinovarobotics.com/uploads/User-Guide-Gen3-R07.pdf), on page 199, the link length is defined as 0.615.

corrected the last link legth of Kinova Gen3

---

robosuite/controllers/controller_factory.py

There is a typo in `arm_controller_factory` for the joint controllers.

fix typo: "genereic" to "generic"

---

robosuite/models/arenas/multi_table_arena.py

Some of the files in branch v1.4.1 already have the `import Iterable` modified to be compatible with `python 3.10` but this one does not. Updating it.
@otokatli

`from collections` ➡️ `from collections.abc`

---

robosuite/wrappers/gym_wrapper.py

The output type of `reset` of `GymWrapper` didn't match the type on its docstring, so I fixed the docstring instead of removing empty dict (which was gonna result in breaking changes in some demo scripts).

fix gym_wrapper docstring

---

.github/workflows/run-tests.yaml
requirements-extra.txt

Add robosuite_models to requirements-extra

Add robosuite_models to requirements-extra

---

README.md
robosuite/controllers/parts/controller.py
robosuite/controllers/parts/mobile_base/mobile_base_controller.py
robosuite/models/grippers/jaco_three_finger_gripper.py
tests/test_controllers/test_linear_interpolator.py
tests/test_controllers/test_variable_impedance.py
tests/test_grippers/test_all_grippers.py
tests/test_grippers/test_panda_gripper.py
tests/test_grippers/test_rethink_gripper.py

Fixes to pass jaco gripper test, linear interpolation, variable impedance tests.

Fix for test cases

---

docs/basicusage.md
docs/demos.md
docs/installation.md

Add an explanation to mac users to prepend the python command with mj, if they're using the mjviewer.
Added to various sections of the introductory docs.
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.
**Note**: Before submitting this PR, please read the [contributor guideline](https://github.com/ARISE-Initiative/robosuite/blob/master/CONTRIBUTING.md).

add instructions for mac users in docs

---

robosuite/demos/demo_gym_functionality.py
robosuite/wrappers/gym_wrapper.py

When running `python robosuite/demos/demo_gym_functionality.py`, the rendering freezes after the first ep. To fix this, we need to run `env.close()` at the end of each ep to re-initialize the renderer for the next ep.
Examples:
```
python robosuite/demos/demo_gym_functionality.py
```
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.
**Note**: Before submitting this PR, please read the [contributor guideline](https://github.com/ARISE-Initiative/robosuite/blob/master/CONTRIBUTING.md).

fix demo_gym_functionality rendering issues after first ep

---

robosuite/demos/demo_collect_and_playback_data.py
robosuite/demos/demo_composite_robot.py
robosuite/demos/demo_control.py
robosuite/demos/demo_device_control.py
robosuite/demos/demo_gripper_selection.py
robosuite/demos/demo_random_action.py
robosuite/demos/demo_renderers.py
robosuite/scripts/collect_human_demonstrations.py

Add max frame rate feature to relevant demo scripts, to make speed stable across platforms, and by default close to real time.
Examples:
```
mjpython robosuite/scripts/collect_human_demonstrations.py --environment Lift --device spacemouse --camera frontview --robots GR1FixedLowerBody --max_fr 25
```
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.
**Note**: Before submitting this PR, please read the [contributor guideline](https://github.com/ARISE-Initiative/robosuite/blob/master/CONTRIBUTING.md).

add max frame rate feature to relevant demo scripts

---

docs/overview.md
robosuite/demos/demo_video_recording.py

Update overview page text

---

robosuite/demos/demo_segmentation.py

Fix seg demo script. For some machines, using the default `renderer=mjviewer` leads to implausible segmentations. Updating to `renderer=mujoco` appears to fix this issue for some machines.
Explain/show how you tested your changes.
```bash
python robosuite/demos/demo_segmentation.py
```

Fix seg demo script

---

robosuite/controllers/config/default/composite/whole_body_mink_ik.json
robosuite/devices/device.py
robosuite/examples/third_party_controller/mink_controller.py
robosuite/utils/ik_utils.py

Fix `whole_body_ik` config bug.
Add a default `whole_body_mink_ik` config so that other robots can also use this control mode.
|  Title               | Label           |
|----------------------|-----------------|
| Fixes #549        | (🐛 Bug)        |
- Set `input_type=absolute` for part controllers in `whole_body_ik`  config
- Copied a GR1 mink IK control config as the default `whole_body_mink_ik` config. A validation function was added for the mink controller to check the keys in the config.
```bash
python robosuite/scripts/collect_human_demonstrations.py --environment Lift --camera frontview --robots Panda --controller WHOLE_BODY_IK
python robosuite/scripts/collect_human_demonstrations.py --environment Lift --camera frontview --robots Panda --controller WHOLE_BODY_MINK_IK
```

[fix] fix whole_body_ik config and add a default whole_body_mink_ik config

---

docs/demos.md

Update demo docs w/ teleop usage info

Update demo docs w/ teleop usage info

---

robosuite/robots/fixed_base_robot.py

Remove unneeded print

---

robosuite/devices/spacemouse.py

Adds helpful error message when SpaceMouse USB device is in use by another process.
Specifically guides users to close `3DconnexionHelper` on macOS, a common cause of device access conflicts.
1. macOS: Have `3DconnexionHelper` running (reproduces device conflict)
2. Run demo with `--device spacemouse` to see error message

Add troubleshooting message for spacemouse failure to open

---

docs/modules/controllers.rst
robosuite/controllers/composite/composite_controller_factory.py
robosuite/controllers/config/default/composite/basic.json
robosuite/controllers/config/default/composite/hybrid_mobile_base.json
robosuite/controllers/config/default/composite/whole_body_ik.json
robosuite/controllers/config/default/composite/whole_body_mink_ik.json
robosuite/controllers/config/robots/default_baxter.json
robosuite/controllers/config/robots/default_gr1.json
robosuite/controllers/config/robots/default_gr1_fixed_lower_body.json
robosuite/controllers/config/robots/default_gr1_floating_body.json
robosuite/controllers/config/robots/default_iiwa.json
robosuite/controllers/config/robots/default_kinova3.json
robosuite/controllers/config/robots/default_panda.json
robosuite/controllers/config/robots/default_panda_dex.json
robosuite/controllers/config/robots/default_pandaomron.json
robosuite/controllers/config/robots/default_sawyer.json
robosuite/controllers/config/robots/default_spotwitharm.json
robosuite/controllers/config/robots/default_tiago.json
robosuite/controllers/config/robots/default_tiago_whole_body_ik.json
robosuite/controllers/config/robots/default_ur5e.json
robosuite/examples/third_party_controller/default_mink_ik_gr1.json
robosuite/robots/robot.py
tests/test_controllers/test_variable_impedance.py

In the composite controller configs, change the keyword from `body_parts_controller_configs` -> `body_parts`. The name is simpler and it unifies the convention between the internal code naming convention and the json files
Ran `python -m pytest` and everything passed.
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.
**Note**: Before submitting this PR, please read the [contributor guideline](https://github.com/ARISE-Initiative/robosuite/blob/master/CONTRIBUTING.md).

simplify composite controller keyword for body_parts

---

.github/workflows/run-tests.yaml
tests/test_renderers/test_all_renderers.py

Fixes #556 
Rendering test doesn't work properly if no display available. Skip screen rendering tests if no display available.
`pytest`

Have CI check all `tests/`

---

robosuite/controllers/config/default/parts/osc_pose.json
robosuite/controllers/config/default/parts/osc_position.json

Resolves #565 
run `demo_control.py` with OSC_POSE/OSC_POSITION which load the json.

update part controller jsons

---

robosuite/renderers/context/egl_context.py

In python 3.12 the way that ctypes works with PyOpenGL is slightly stricter, meaning that what worked before due to a silent cast now crashes.
This addresses the issue here: https://github.com/ARISE-Initiative/robosuite/issues/569
Ran the tests (they worked) and also tried the snippet on python 3.12 and 3.11 and it also worked
Use python 3.12 and try to use the snippet I mentioned in issue #569

Fixes #569 (🐛 Bug) 

---

docs/algorithms/demonstrations.md
docs/modules/devices.md
docs/simulation/device.rst

Update devices + related docs
Addresses part of #554

Update devices + related docs

---

robosuite/models/assets/grippers/fourier_left_hand.xml
robosuite/models/assets/grippers/fourier_right_hand.xml

This PR will match the orientation of the Fourier hands with the Inspire hands.
There should be no visual difference for the hands before and after the fix. However, it fixes the additional sites and helps future extensibility.

Match the orientation of the fourier hands with the inspire hands

---

robosuite/controllers/parts/arm/osc.py

This PR should fix https://github.com/ARISE-Initiative/robosuite/issues/562
Running OSC_POSE worked but OSC_POSITION would result in the following error:
```
Traceback (most recent call last):
File "/archive/tmp/reproduce_v15.py", line 56, in <module>
obs, reward, done, info = env.step(action)
File "/home/soroushn/code/robosuite/robosuite/environments/base.py", line 452, in step
self._pre_action(action, policy_step)
File "/home/soroushn/code/robosuite/robosuite/environments/robot_env.py", line 589, in _pre_action
robot.control(robot_action, policy_step=policy_step)
File "/home/soroushn/code/robosuite/robosuite/robots/fixed_base_robot.py", line 146, in control
self.composite_controller.set_goal(action)
File "/home/soroushn/code/robosuite/robosuite/controllers/composite/composite_controller. …
```

osc position fixes

---

robosuite/models/robots/manipulators/legged_manipulator_model.py

Fix equality dependency when removing joint actuation.

[fix] fix equality removal with actuator removal

---

robosuite/demos/demo_domain_randomization.py
robosuite/utils/log_utils.py
robosuite/wrappers/domain_randomization_wrapper.py

Update domain randomization wrapper to work with  mujoco!=3.1.1 for some settings.
Previously, couldn't use script at all if mujoco!=3.1.1.
`python robosuite/demos/demo_domain_randomization.py`

Update domain randomization wrapper to work with  mujoco!=3.1.1 for some settings

---

docs/changelog.md
docs/conf.py
robosuite/__init__.py
robosuite/renderers/context/egl_context.py
setup.py

Bump versions, update changelog for v1.5.1.

Bump version 1.5.0 -> 1.5.1

---

.github/workflows/update-docs.yaml

When building it looks like documentation pages have an error where the built docs are not the same as what is displayed on the website. For example, the webpage https://robosuite.ai/docs/simulation/device.html is empty despite the https://github.com/ARISE-Initiative/robosuite/blob/master/docs/simulation/device.rst having more information. I suspect this is due to the fact the built docs are being synchronized with the its parent directory: https://github.com/ARISE-Initiative/robosuite/blob/master/.github/workflows/update-docs.yaml#L44
I have updated the workflow to circumvent this issue, but I am not 100% sure if this is the cause/the changes I made are the solution (can't fully test locally).
Was able to replicate the error by running `rsync -av --delete docs/_build/html/ docs/`  and …

potential fix to build and docs synchronization error

---

.github/workflows/update-docs.yaml

Adds `hidapi` for rendering spacemouse related documentation under simulation API/devices. Not importing this module could have potentially been what is causing the page to not render correctly.
I built the website on my Mac and the Spacemouse related information rendered properly with no exception (an exception was thrown earlier and Spacemouse related information did not render).

Adding hdiapi to imports for docs for spacemouse

---

docs/modules/renderers.md
robosuite/scripts/render_dataset_with_omniverse.py
robosuite/utils/usd/exporter.py
robosuite/utils/usd/objects.py

Adding normals and semantic segmentation render modalities.

Adding render modalities

---

requirements-extra.txt
setup.py

Adding requirements to requirements-extra.txt for USD rendering.

Adding USD requirements to requirements-extra

---

robosuite/demos/demo_random_action.py
robosuite/environments/manipulation/manipulation_env.py
robosuite/utils/input_utils.py

Add all manipulators in https://robosuite.ai/docs/modules/robots.html#manipulators to demo_random_action by default
`python robosuite/demos/demo_random_action.py`, then select `GR1` option

Add all manipulators to demo_random_action by default

---

robosuite/macros.py
robosuite/robots/robot.py

Fix the the following warning message:
robosuite/robosuite/robots/robot.py:151: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

Replace warn with warning

---

robosuite/models/robots/compositional.py

Change the mounting direction for PandaDexHR and PandaDexHL, previously the fingers are pointing forward. Now the hand is pointing downward.

fix the mounting direction of dex hand for panda robot

---

robosuite/models/objects/composite/pot_with_handles.py

The current pot_with_handles object will result in a wrong shape when `size[0] != size[1]` One line change can fix this.

fix pot with handles when pot is rectangle

---

robosuite/robots/robot.py

Explain what this PR does. Feel free to tag your PR with the appropriate label(s).
Examples:
|  Title               | Label           |
|----------------------|-----------------|
| Fixes #[issue]       | (🐛 Bug)        |
| Optimizes something  | (⚡️ Performance) |
| Adds a new feature   | (✨ Feature)     |
Explain/show how you tested your changes.
Examples:
- Added `test_something` in `tests/test_stuff.py`.
- Added `new_feature` and checked that training converges with policy X on dataset/environment Y.
- Optimized `some_function`, it now runs X times faster than previously.
Provide a simple way for the reviewer to try out your changes.
Examples:
```bash
DATA_DIR=tests/data pytest -sx tests/test_stuff.py::test_something
```
```bash
python robosuite/scripts/train.py --some.option=true
``` …

Add the joint pos obs back

---

.github/workflows/update-pypi.yaml
setup.py

Adds a CI/CD action for updating PyPI. This is currently for test PyPI. The action will run in any of the following three cases:
1. When a new commit is pushed to the PyPI branch (for testing purposes)
2. When the workflow is manually triggered
3. When a new release is published

PyPI Publishing GitHub Action

---

robosuite/examples/third_party_controller/mink_controller.py

fix frame transformation for delta action input with both base & world frame reference. The fixed robot movement is shown in the video. Left: base, delta; Right: base, absolute. Under absolute mode, the robot will move faster. Not sure if there is an action scaling for this mode.
https://github.com/user-attachments/assets/c2aacab1-e964-4af4-b0ce-89b201caab7b

[fix] fix mink IK with delta input type

---

robosuite/demos/demo_segmentation.py
robosuite/models/tasks/task.py

Enable instance segmentation to include bodies in arena.
Before fix:
After fix:
`python robosuite/demos/demo_segmentation.py --segmentation-level instance --random-colors --env-name NutAssemblySquare --camera agentview`

Enable instance segmentation to include bodies in arena

---

docs/algorithms/demonstrations.md
docs/conf.py
docs/demos.md
docs/installation.md
docs/modules/devices.md
docs/overview.md
docs/simulation/device.rst
docs/source/robosuite.devices.rst
robosuite/demos/demo_device_control.py
robosuite/demos/demo_sensor_corruption.py
robosuite/demos/demo_usd_export.py
robosuite/devices/__init__.py
robosuite/devices/dualsense.py
robosuite/macros.py
robosuite/scripts/collect_human_demonstrations.py

Recently I try to integrate my DualSense controller with robosuite to teleoperate the simulated robot. I finish it and I think maybe we can merge the feature into Robosuite official codebase
|  Title               | Label           |
|----------------------|-----------------|
| Dualsense device support   | (✨ Feature)   Added [Sony PS5 DualSense](https://www.playstation.com/en-us/accessories/dualsense-wireless-controller/) device support for teleoperating simulated robot in environment  |
**PS: The doc has not been updated. If Robosuite has a plan to add this feature,  I will commit to update.**
- Added `dualsense` option for `device` arg in `demos/demo_device_control.py`.
- Test with real dualsense controller in MacOS and Unbuntu20.04.
Connect your dualsense to your computer through USB …

feat: Dualsense device support

---

robosuite/models/tasks/task.py

Including `left_eef_target` and `right_eef_target` in id_mappings messes up dataset collected w/o `left_eef_target` and `right_eef_target`. Also, these targets aren't part of the task --- they're included for the `mjgui` device.
Remove `left/right_eef_target` from id mappings.
Loading dataset collected using `robosuite<1.5.0`

Hot fix `Task.generate_id_mappings()`: remove `left/right_eef_target` from id mappings

---

robosuite/environments/manipulation/door.py
robosuite/environments/manipulation/lift.py
robosuite/environments/manipulation/pick_place.py
robosuite/environments/manipulation/stack.py
robosuite/environments/manipulation/tool_hang.py
robosuite/environments/manipulation/wipe.py

Allow `base_type` specification in manipulation envs

Allow base_type specification in manipulation envs

---

docs/algorithms/demonstrations.md
robosuite/environments/base.py
robosuite/environments/manipulation/manipulation_env.py
robosuite/environments/robot_env.py
robosuite/scripts/collect_human_demonstrations.py

Testing command:
python -m robocasa.scripts.collect_demos --robots GR1ArmsOnlyFourierHands --controller ~/repos/robosim/robocasa/robocasa/examples/third_party_controller/default_mink_ik_gr1.json --device keyboard --camera egoview egoview egoview --ik_indicator --env PosttrainPnPNovelFromPlacematToPlateSplitA --store_collected_demo --renderer mujoco

Support multiple cameras

---

robosuite/devices/device.py
robosuite/models/grippers/fourier_hands.py
robosuite/models/grippers/inspire_hands.py

- Adding grasping qpos for Inspire and Fourier hands. Used it when treating the hand as a gripper, only control its open/close pose.
- Using this qpos to set the hand action cmd in the device control class.

[add] add grasp qpos for inspire and fourier hand

---

robosuite/wrappers/data_collection_wrapper.py

Fix issue with resets in data collection wrapper. The `reset` function in the wrapper calls the `_start_new_episode` function, which in turn calls the `env.reset_from_xml_string` function. There is essentially two resets happening in this operation. The second reset needs to be consistent with the first one, but there is no way to ensure that currently. It only started to become an issue after I implemented randomized robot base resets. The way to ensure this is to save and set the episode meta data before calling the second reset (courtesy `env.reset_from_xml_string`). Also, we have to remember to unset the reset afterwards.
I used the [collect_demos.py](https://github.com/robocasa/robocasa/blob/main/robocasa/scripts/collect_demos.py) script in RoboCasa to test this, and the issue with …

data collection wrapper resets

---

robosuite/renderers/context/egl_context.py

This small PR fixes the missing evaluation of the `PYOPENGL_PLATFORM` environment variable in the exception:
```
ImportError: Cannot use EGL rendering platform. The PYOPENGL_PLATFORM environment variable is set to {!r} (should be either unset or 'egl').
```
Run tests

Ensure EGL ImportError includes PYOPENGL_PLATFORM value

---

robosuite/models/assets/robots/baxter/robot.xml
setup.py

Fixes #681 
With these fixes there should not be any issue with initializing Baxter with Mujoco >= 3.3.0. However, initializing Baxter with an earlier version will cause issues.
Refer to mujoco [changelog](https://mujoco.readthedocs.io/en/3.3.0/changelog.html) for version 3.3.0, item 10 for justification on why the fix works.
Also adds `qpsolvers[quadprog]>=4.3.1` to setup.py to make tests using Mink to pass
run `python robosuite/scripts/collect_human_demonstrations.py` with Baxter and Mujoco >= 3.3.0. With these changes it should work fine. Without it will not work.

fix baxter mesh issues

---

robosuite/robots/robot.py

Fixes #673 
To test change the basic controller to use JOINT_POSITION for grippers. (change the this [line](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/controllers/config/default/composite/basic.json#L46) to `"type": "JOINT_POSITION"`). Then run `python robosuite/scripts/collect_human_demonstrations.py --environment Lift`
Before the changes in this branch, the script will have an exception. After the changes controlling the gripper with JOINT_POSITION control should work fine.

update part controller config to include joint indices

---

robosuite/environments/manipulation/manipulation_env.py
robosuite/environments/robot_env.py

Updated the comments in manipulation_env.py and robot_env.py.
Initially in the class description for the base/mount type, it was mentioned to use None. 
Changed this None to "NullMount" since the old comment was not accurate.

Updating base type comments

---

robosuite/models/arenas/arena.py
robosuite/models/objects/objects.py
robosuite/utils/mjcf_utils.py

fixes https://github.com/robocasa/robocasa/issues/154.
The latest commit that refactors `set_scale` sets the scale for sites under the `self._obj` however, it should be looking for sites under `self.worldbody` (as done prior to the latest commit in master commit)
`python -m robocasa.demos.demo_kitchen_scenes` using public main of robocasa
run above command with this branch and with master. With this branch it should work, on master will get error 
`ValueError: Overhang value is too large, must be lower than front padding (-0.22)`

fix site scaling to get all sites from world body

---

robosuite/controllers/parts/mobile_base/joint_vel.py
robosuite/models/assets/bases/floating_legged_base.xml
robosuite/models/assets/bases/null_mobile_base.xml
robosuite/models/assets/bases/omron_mobile_base.xml

Currently, for mobile base xmls, "forward" means "side" while "side" means forward. Consequently `mobile_base/joint_vel.py` has a mysterious action switching logic.
Fix mobile base xml so forward means forward (x axis), side means sid…e (y-axis); fix controller's weird x-y axis switching logic.
`python robosuite/scripts/collect_human_demonstrations.py --robots PandaOmron` still works as expected.

Fixes mobile base xmls and controller logic

---

robosuite/models/objects/objects.py
robosuite/utils/mjcf_utils.py

Re-enable scaling for mujoco objects. Got removed in commit 136ac6a8244134d742590c868a5be6a5add318f9

Enable scaling for mujoco object
